learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from learning_log import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("learning_logs.urls")),
    path("__debug__/", include("debug_toolbar.urls"))
    # path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Панель Администрирования"
admin.site.index_title = "Известные люди мира"

learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""

from django.urls import path, re_path, register_converter
from . import views
from . import converters
#
# register_converter(converters.FourDigitYearConverter, "yyyy")
#
# app_name = 'learning_logs'

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('addpage/', views.addpage, name='addpage'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login, name='login'),
    path('post/<slug:post_slug>/', views.show_post, name='post'),
    path('category/<slug:cat_slug>/', views.show_category, name='category'),
    path('tag/<slug:tag_slug>/', views.show_tag_by_postlist, name='tag')







#     path('topics/', views.topics, name='topics'),
#     path('topics/<int:topic_id>/', views.topic, name='topic'),
#     path('new_topic/', views.new_topic, name='new_topic'),
#     path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
#     path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
#     path('tests/', views.tests),
#     path('tests/<int:tests_id>/', views.test_id),
#     path('tests/<slug:tests_slug>/', views.test_slug, name='test'),
#     path('archive/<yyyy:year>/', views.archive)
]

users/urls.py
from django.urls import path, include

app_name = 'users'

'''Включение авторизаций по умолчанию'''
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
]

learning_logs/models.py
from django.db import models
from django.db.models import PROTECT
from django.template.defaultfilters import slugify
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=1)


class Women(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="Slug")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', default=None, blank=True,
                              null=True, verbose_name='Фото')
    content = models.TextField(blank=True, verbose_name="Текст статьи")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Дата создание")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    is_published = models.BooleanField(default=True, verbose_name="Статус")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name="Категория")
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags', verbose_name="Теги")
    husband = models.OneToOneField('Husband', blank=True, on_delete=models.SET_NULL, null=True, related_name='women', verbose_name="Муж")

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        verbose_name = "Известные люди"
        verbose_name_plural = "Известные люди"
        ordering = ['time_create']
        indexes = [
            models.Index(fields=['-time_create'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})




class TagPost(models.Model):
    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True)

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})




class Husband(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    m_count = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return self.name

class UploadFiles(models.Model):
    file = models.FileField(upload_to='uploads_model/')


# class Topic(models.Model):
#     text = models.CharField(max_length=200)
#     date_add = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.text
#
# class Entry(models.Model):
#     '''Inforamtion learned by user about topic'''
#     topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
#     text = models.TextField()
#     date_added = models.DateTimeField(auto_now_add=True)
#
#     class Meta():
#         verbose_name_plural = 'entries'
#
#     def __str__(self):
#         '''Returns string view of model'''
#         text_preview = f'{self.text[:50]}...' if len(self.text) > 50 else self.text
#         return text_preview

learning_logs/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.forms import TextInput, Textarea
from django.utils.deconstruct import deconstructible
from .models import Category, Husband, Women, TagPost



@deconstructible
class RussianValidator:
    ALLOWED_CHARS = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя0123456789-"
    code = 'russian'

    def __init__(self, message=None):
        self.message = message if message else "Должны присутствовать латинские символы, дефис и пробел"

    def __call__(self, value, *args, **kwargs):
        if not set(value) <= set(self.ALLOWED_CHARS):
            raise ValidationError(self.message, code=self.code)


class AddPostForm(forms.ModelForm):
    cat = forms.ModelChoiceField(queryset=Category.objects.all(), label='Категория', empty_label='Категория не выбрана')
    husband = forms.ModelChoiceField(queryset=Husband.objects.all(), required=False, label='Муж',empty_label='Не замужем')

    tags = forms.ModelMultipleChoiceField(
        queryset=TagPost.objects.all(),
        required=False,
        widget=forms.SelectMultiple(attrs={'size': 6}),  # Виджет с множественным выбором
        label="Теги",
    )

    class Meta:
        model = Women
        fields = ['title', 'slug', 'content', 'photo', 'is_published', 'cat', 'husband', 'tags', ]
        widgets = {
            'title': TextInput(attrs={'class': 'form-input'}),
            'content': Textarea(attrs={'cols': 50, 'rows': 5}),
            # 'tags': )
        }
        labels = {'slug': 'URL'}

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            raise ValidationError("Длина превышает 50 символов")
        elif len(title) < 5:
            raise ValidationError("Длина должна быть больше 5 символов")
        return title


class UploadFileForm(forms.Form):
    file = forms.FileField(label='Файл')


#
# class TopicForm(forms.ModelForm):
#     class Meta:
#         model = Topic
#         fields = ['text']
#         labels = {'text': 'New Topic Name'}
#
# class EntryForm(forms.ModelForm):
#     class Meta:
#         model = Entry
#         fields = ['text']
#         labels = {'text': 'Entry'}
#         widgets = {'text': forms.Textarea(attrs={'cols': 120})}
#

learning_logs/views.py
import uuid
import os
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AddPostForm, UploadFileForm
from .models import Women, Category, TagPost, UploadFiles
# from .forms import TopicForm, EntryForm
from django.http import HttpResponse, HttpResponseNotFound, Http404, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.urls import reverse
from django.template.loader import render_to_string


menu = [
    {"title":"About us", "url_name": "about"},
    {"title":"Add post", "url_name": "addpage"},
    {"title":"Returning call", "url_name": "contact"},
    {"title":"Enter", "url_name": "login"}
]

cats_db = [
    {'id': 1, 'name': 'Actors'},
    {'id': 2, 'name': 'Singers'},
    {'id': 3, 'name': 'Sportsmen'},
]

def index(request):
    posts = Women.published.all().select_related('cat').order_by('-time_create')
    data = {
        'title': 'Main Page',
        'posts': posts,
        'menu': menu,
        'cat_selected': 0,
    }
    return render(request, 'learning_logs/index-learn.html', context=data)

# def handle_upload_file(f):
#     ext = os.path.splitext(f.name)[-1]
#     unique_filename = f"{uuid.uuid4()}{ext}"
#     save_path = os.path.join("learning_log/uploads/", unique_filename)
#     with open(save_path, "wb+") as destination:
#         for chunk in f.chunks():
#             destination.write(chunk)


def about(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            # handle_upload_file(form.cleaned_data['file'])
            fp = UploadFiles(file=form.cleaned_data['file'])
            fp.save()
    else:
        form = UploadFileForm()
        # handle_upload_file(request.FILES['file_upload'])
    #     form = UploadFileForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         # handle_upload_file(form.cleaned_data['file'])
    #         fp = UploadFiles(file=form.cleaned_data['file'])
    #         fp.save()
    # else:
    #     form = UploadFileForm()
    #
    return render(request, 'learning_logs/about-learn.html',
                  {'title': 'about Site', 'menu': menu, 'form': form})


def addpage(request):
    if request.method == "POST":
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # # print(form.cleaned_data)
            # try:
            #     Women.objects.create(**form.cleaned_data)
            #     return redirect('home ')
            # except:
            #     form.add_error(None, "Ошибка Добавления поста")
            return redirect('home')
    else:
        form = AddPostForm()

    date = {
        'menu': menu,
        'title': 'Adding new page',
        'form': form,
    }
    return render(request, 'learning_logs/addpage.html', date)

def contact(request):
    return HttpResponse("Returning call")

def login(request):
    return HttpResponse("Autorization")

def show_category(request, cat_slug):
    category = get_object_or_404(Category, slug=cat_slug)
    posts = Women.published.filter(cat_id=category.pk).select_related('cat')
    data = {
        'title': f'Category: {category.name}',
        'posts': posts,
        'menu': menu,
        'cat_selected': category.pk
    }
    return render(request, 'learning_logs/index-learn.html', context=data)


def show_post(request, post_slug):
    post = get_object_or_404(Women, slug=post_slug)
    data = {
        'title': post.title,
        'post': post,
        'menu': menu,
        'cat_selected': 1,
    }

    return render(request, 'learning_logs/post.html', data)


def show_tag_by_postlist(request, tag_slug):
    tag = get_object_or_404(TagPost, slug=tag_slug)
    posts = tag.tags.filter(is_published=1).select_related('cat')
    data = {
        'title': f'Tag: {tag.tag}',
        'posts': posts,
        'menu': menu,
        'cat_selected': None,
    }

    return render(request, 'learning_logs/index-learn.html', context=data)




# def index(request):
#     return render(request, 'learning_logs/index.html')
#
# def topics(request):
#     topics = Topic.objects.order_by('date_add')
#     context = {'topics': topics}
#     return render(request, 'learning_logs/topics.html', context)
#
# def topic(request, topic_id):
#     topic = Topic.objects.get(id=topic_id)
#     entries = topic.entry_set.order_by('-date_added')
#     context = {'topic': topic, 'entries': entries}
#     return render(request, 'learning_logs/topic.html', context)
#
# def new_topic(request):
#     '''defining a new topic'''
#     if request.method != 'POST':
#         form = TopicForm()
#     else:
#         form = TopicForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('learning_logs:topics')
#
#     #Returning empty form
#     context = {'form': form}
#     return render(request, 'learning_logs/new_topic.html', context)
#
# def new_entry(request, topic_id):
#     '''definding a new entry'''
#     topic = Topic.objects.get(id=topic_id)
#     if request.method != 'POST':
#         form = EntryForm()
#     else:
#         form = EntryForm(data=request.POST)
#         if form.is_valid():
#             new_entry = form.save(commit=False)
#             new_entry.topic = topic
#             new_entry.save()
#             return redirect('learning_logs:topic', topic_id=topic_id)
#
#     # Returning empty form
#     context = {'form': form, 'topic': topic}
#     return render(request, 'learning_logs/new_entry.html', context)
#
# def edit_entry(request, entry_id):
#     '''Redacting current entry'''
#     entry = Entry.objects.get(id=entry_id)
#     topic = entry.topic
#     if request.method != "POST":
#         form = EntryForm(instance=entry)
#     else:
#         form = EntryForm(instance=entry, data=request.POST)
#         form.save()
#         return redirect('learning_logs:topic', topic_id=topic.id)
#
#     context = {'entry': entry, 'topic': topic, 'form': form}
#     return render(request, 'learning_logs/edit_entry.html', context)
#

learning_logs/templates/learning_logs/about-learn.html
{% extends 'base.html' %}

{% block content %}
<p>{{ title }}</p>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Send</button>
</form>
{% endblock %}

learning_logs/templates/learning_logs/addpage.html
{% extends 'base.html' %}

{% block content%}
<h1>{{title}}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Send</button>
</form>
{% endblock %}

learning_logs/templates/learning_logs/base.html
<div>
  <a href="{% url 'learning_logs:index' %}">Learning log</a> -
  <a href="{% url 'learning_logs:topics' %}">Topics</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <form action="{% url 'users:logout' %}" method="post" style="display:inline;">
      {% csrf_token %}
      <a href="#" onclick="this.closest('form').submit();">Log out</a>
    </form>
  {% else %}
    <a href="{% url 'users:login' %}">Log in</a>
  {% endif %}
</div>


{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">save changes</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index-learn.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
		<li><div class="article-panel">
			<p class="first">Category: {{ p.cat.name }}</p>
			<p class="last">Date: {{ p.time_update|date:"d-m-Y H:i:s" }}</p>
		</div>
			{% if p.photo %}
			<p><img class="img-article-left thumb" src="{{ p.photo.url }}"></p>
			{% endif %}
			<h2>{{p.title}}</h2>
	{% autoescape off %}
	{{ p.content|linebreaks|truncatewords:35 }}
	{% endautoescape %}
		<div class="clear"></div>
		<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
		</li>
	{% endfor %}
</ul>
{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're
learning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/list_categories.html
{% for cat in cats %}
{% if cat.id == cat_selected %}
<li class="selected">{{cat.name}}</li>
{% else %}
<li><a href="{{ cat.get_absolute_url }}">{{cat.name}}</a></li>
{% endif %}
{% endfor %}

learning_logs/templates/learning_logs/list_tags.html
{% if tags %}
    <p>Теги:</p>
    <ul class="tags-list">
        {% for tag in tags %}
        <li><a href="{{ tag.get_absolute_url }}">{{tag.tag}}</a></li>
        {% endfor %}
    </ul>
{% endif %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add topic</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/post.html
{% extends 'base.html' %}

{% block content %}
<!--Теги-->
{% block breadcrumbs %}
{% with post.tags.all as tags %}
{% if tags %}
<ul class="tags-list">
    <li>Tags:</li>
    {% for tag in tags %}
    <li><a href="{{ tag.get_absolute_url }}">{{tag.tag}}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% endblock %}

<h1>{{ title }}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{ post.photo.url }}"></p>
{% endif %}

{{post.content|linebreaks}}
{% endblock%}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>

<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>

<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
        {% if not forloop.last %}
            <hr>
        {% endif %}
    </li>
    {% empty %}
        <li> There are no entries for the topic yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>Topics</p>

    <ul>
        {% for topic in topics %}
            <li>
                <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'learning_logs:new_topic' %}">Add new topic</a>

{% endblock content %}